### PR TITLE
use graphical icon that not just repeats the name

### LINKED ISSUE #41: use a different icon that does not just repeat the name
while maybe stylish, set in context where the icon is usually used, this looks repetitive and a bit weird, esp. as the icon has also white background:

Screenshot 2023-01-19 at 13 59 20

if course, this is not "wrong" and other apps can pick up this style, but we should not use that as a pattern we provide.

as an alternative, i suggest to use a waving hand as the icon, with a non-white background. 👋

once this is done here, we should also adapt corkboard and checklist that also repeat the name in the icons.

### PR DESCRIPTION
**Pull request by r10s**
the old icon just uses the text "hello" black on white.

while maybe stylish,
set in context where the icon is usually used,
this looks repetitive and a bit weird,
esp. as the icon has also white background.

of course, this is not "wrong" and other apps can pick up this style, but we should not use that as a default pattern we encourage ppl to use.

also, my idea is to have sth more "funny" and "shiny", not sure if that was successful :)
starburst inspired from https://codepen.io/lethargic/pen/aBybeK , the hand is just an emoji,
put together with gimp - if someone want to do a vector or has another idea, this is very welcome :)

before / after:

  

closes #41

### CODE REVIEW

**Review by adbenitez — APPROVED** [review]
WOW I love that icon, almost hurts me that it is wasted in an example/template app :ok_hand:

**Comment by r10s** [comment]
> btw, hope there are no weird copyright nonsense with that emoji?

hm, good questions, idk. if you know of a  similar "hand" where we know that it is free-for-being-used, i can recreate the icon on top of that. just to be sure, as this questions is raised now :) - i _assume_ it is okay to use an emoji glyph the way we are doing above.

**Comment by r10s** [comment]
answering myself: i think we should be able to use the emoji from "Noto" license-wise,  https://github.com/googlefonts/noto-emoji , that emoji even fits better to the backgou d as being more flat

**Review by rosano — APPROVED** [review]
Looks great and definitely more fun. The old one was really a placeholder so good to replace it. I would have centered the starburst a bit more but I think off center can be interesting too. Nice to think about 'templates' also, maybe we can do what Apple does and have a default template PSD, or a collection with patterns like the starburst. 👍🏽

**Review by WofWca — APPROVED** [review]

**Pull request merged**
